name: build-and-push
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Multi-arch (para amd64 e arm64)
      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      # Gera tags/labels (minúsculas e estáveis)
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/seerr-custom2
          tags: |
            type=raw,value=latest
            type=sha,format=short
          flavor: |
            latest=true
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
